- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/monitoring
    - /opt/monitoring/backups

- name: Deploy Docker Compose config
  template:
    src: docker-compose-monitoring.yml.j2
    dest: /opt/monitoring/docker-compose.yml

- name: Deploy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /opt/monitoring/prometheus.yml

- name: Deploy Alertmanager config
  template:
    src: alertmanager.yml.j2
    dest: /opt/monitoring/alertmanager.yml

- name: Start services
  command: docker-compose up -d
  args:
    chdir: /opt/monitoring

- name: Schedule backups
  cron:
    name: "Monitoring backups"
    job: "/opt/monitoring/backup.sh"
    hour: 2
    minute: 0
