all:
  children:
    monitoring:                 # Группа серверов мониторинга
      hosts:
        monitoring.example.com:
          ansible_host: "localhost"
          ansible_port: "33332"
          ansible_user: "root"
          ansible_ssh_pass: "root"  # Правильное имя переменной для пароля SSH
          ansible_sudo_pass: "root"  # Добавлена недостающая кавычка
    target:                     # Группа целевых серверов
      hosts:
        target.example.com:
          ansible_host: "localhost"
          ansible_port: "3332"
          ansible_user: "root"
          ansible_ssh_pass: "root"
          ansible_sudo_pass: "root"