all:
  children:
    monitoring:                 # Группа серверов мониторинга
      hosts:
        monitoring.example.com:
          ansible_host: 192.168.1.100
    target:                     # Группа целевых серверов
      hosts:
        target.example.com:
          ansible_host: 192.168.1.200